# Generated by Django 3.2.6 on 2023-03-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historia', models.IntegerField()),
                ('id_paciente', models.IntegerField()),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('anio_nacimiento', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('motivo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
