# Generated by Django 3.2.6 on 2023-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejadorhistorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
